/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.roger.agenda;

import java.awt.Color;
import java.awt.Dimension;
import java.io.UnsupportedEncodingException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.security.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author roger
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        fieldUsuario = new javax.swing.JTextField();
        labelSenha = new javax.swing.JLabel();
        fieldSenha = new javax.swing.JPasswordField();
        checkLembrardemim = new javax.swing.JCheckBox();
        btnEntrar = new javax.swing.JButton();
        btnCadastrese = new javax.swing.JButton();
        labelErro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jenda");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(374, 347));

        labelTitulo.setBackground(new java.awt.Color(153, 0, 153));
        labelTitulo.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 24)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setText("Bem-vindo à Jenda!");

        labelUsuario.setBackground(new java.awt.Color(51, 51, 51));
        labelUsuario.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        labelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        labelUsuario.setText("Usuário: ");

        fieldUsuario.setBackground(new java.awt.Color(51, 51, 51));
        fieldUsuario.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        fieldUsuario.setForeground(new java.awt.Color(255, 255, 255));
        fieldUsuario.setToolTipText("Insira seu usuário");
        fieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldUsuarioActionPerformed(evt);
            }
        });

        labelSenha.setBackground(new java.awt.Color(51, 51, 51));
        labelSenha.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        labelSenha.setForeground(new java.awt.Color(255, 255, 255));
        labelSenha.setText("Senha: ");

        fieldSenha.setBackground(new java.awt.Color(51, 51, 51));
        fieldSenha.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        fieldSenha.setForeground(new java.awt.Color(255, 255, 255));
        fieldSenha.setToolTipText("Insira sua senha");

        checkLembrardemim.setBackground(new java.awt.Color(51, 51, 51));
        checkLembrardemim.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        checkLembrardemim.setForeground(new java.awt.Color(255, 255, 255));
        checkLembrardemim.setText("Lembre de mim");
        checkLembrardemim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLembrardemimActionPerformed(evt);
            }
        });

        btnEntrar.setBackground(new java.awt.Color(0, 153, 204));
        btnEntrar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("Entrar");
        btnEntrar.setBorderPainted(false);
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        btnCadastrese.setBackground(new java.awt.Color(102, 102, 102));
        btnCadastrese.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        btnCadastrese.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrese.setText("Cadastre-se");
        btnCadastrese.setBorderPainted(false);
        btnCadastrese.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastreseActionPerformed(evt);
            }
        });

        labelErro.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 10)); // NOI18N
        labelErro.setForeground(new java.awt.Color(255, 0, 51));
        labelErro.setText(".");
        labelErro.setVisible(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelUsuario)
                            .addComponent(labelSenha)
                            .addComponent(fieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(fieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelErro, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkLembrardemim)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCadastrese, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(labelTitulo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(85, 85, 85))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(labelTitulo)
                .addGap(18, 18, 18)
                .addComponent(labelUsuario)
                .addGap(9, 9, 9)
                .addComponent(fieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelSenha)
                .addGap(8, 8, 8)
                .addComponent(fieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkLembrardemim)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrese)
                    .addComponent(btnEntrar))
                .addGap(18, 18, 18)
                .addComponent(labelErro, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Connection con;
    
    private void fieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldUsuarioActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        String query = "SELECT  ID_USUARIO, ATIVO, USUARIO, SENHA_PESSOA from tb_usuario WHERE USUARIO = ? AND SENHA_PESSOA = ?";
        PreparedStatement ps;
        ResultSet rs;
        String usuario = this.fieldUsuario.getText();

        try {
            MessageDigest cryptSenha = MessageDigest.getInstance("SHA-256");
            byte messageDigestSenha[] = cryptSenha.digest(String.valueOf(this.fieldSenha.getPassword()).getBytes("UTF-8"));

            StringBuilder hexString = new StringBuilder();
            for (byte b : messageDigestSenha) {
              hexString.append(String.format("%02X", 0xFF & b));
            }
            String senha_string = hexString.toString();
            
            ConnectionFactory cf = new ConnectionFactory();
            con = cf.getConnection();
            con.setAutoCommit(false);
            ps = con.prepareStatement(query);
            ps.setString(1, usuario);
            ps.setString(2, senha_string);
            rs = ps.executeQuery();
            con.commit();

            int idUsuario = 0;
            boolean ativo = false;
            String usuarioBD = "";
            String senhaBD = "";
            
            while (rs.next()) {
                    idUsuario = rs.getInt("ID_USUARIO");
                    ativo = rs.getBoolean("ATIVO");
                    usuarioBD = rs.getString("USUARIO");
                    senhaBD = rs.getString("SENHA_PESSOA");
            }
            
            if(usuarioBD == ""){
                this.labelErro.setVisible(true);
                this.labelErro.setText("Usuário ou senha inválidos");
            }else{
                System.out.println(usuarioBD);
                if(ativo){
                    boolean logado = true;
                    this.setVisible(false);
                    Tela tela = new Tela();
                    tela.setLogin(idUsuario, logado);
                    tela.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    tela.setVisible(true);  
                    
                    DefaultTableCellRenderer MyCellRender = new DefaultTableCellRenderer();
                    MyCellRender.setBackground(Color.decode("#FFFFFF"));
                    MyCellRender.setForeground(Color.decode("#666666"));
                    MyCellRender.setHorizontalAlignment( JLabel.CENTER );
                    
                    DefaultTableCellRenderer MyHeaderRender = new DefaultTableCellRenderer();
                    MyHeaderRender.setBackground(Color.decode("#000000"));
                    MyHeaderRender.setForeground(Color.decode("#FFFFFF"));
                    MyHeaderRender.setHorizontalAlignment( JLabel.CENTER );
                    
                    tela.tabelContatos.getTableHeader().getColumnModel().getColumn(0).setHeaderRenderer(MyHeaderRender);
                    tela.tabelContatos.getTableHeader().getColumnModel().getColumn(1).setHeaderRenderer(MyHeaderRender);
                    tela.tabelContatos.getTableHeader().getColumnModel().getColumn(2).setHeaderRenderer(MyHeaderRender); 
                    tela.tabelContatos.getTableHeader().getColumnModel().getColumn(3).setHeaderRenderer(MyHeaderRender);
                    tela.tabelContatos.getTableHeader().getColumnModel().getColumn(4).setHeaderRenderer(MyHeaderRender);
                    tela.tabelContatos.setDefaultRenderer(Object.class, MyCellRender);
                }else{
                    this.labelErro.setVisible(true);
                    this.labelErro.setText("O usuario nao se encontra ativo");
                }
            }

            ps.close();
            
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnCadastreseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastreseActionPerformed
        this.setVisible(false);
        TelaCadastro telacadastro = new TelaCadastro();
        telacadastro.setLocationRelativeTo(null);
        telacadastro.setVisible(true);
    }//GEN-LAST:event_btnCadastreseActionPerformed

    private void checkLembrardemimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkLembrardemimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkLembrardemimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrese;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JCheckBox checkLembrardemim;
    private javax.swing.JPasswordField fieldSenha;
    private javax.swing.JTextField fieldUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelErro;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelUsuario;
    // End of variables declaration//GEN-END:variables
}
