CREATE DATABASE AGENDA;

USE AGENDA;

CREATE TABLE TB_USUARIO(
	ID_USUARIO INT NOT NULL auto_increment UNIQUE,
    USUARIO VARCHAR(50) NOT NULL UNIQUE,
    SENHA_PESSOA VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE TB_PESSOA(
	ID_PESSOA INT NOT NULL auto_increment UNIQUE,
    NOME VARCHAR(100) NOT NULL,
    DATA_NASC DATE NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    TELEFONE1 INT NOT NULL,
    TELEFONE2 INT,
    FOTO MEDIUMBLOB,
    ID_USUARIO INT,
    PRIMARY KEY (ID_PESSOA),
    FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO)
);

CREATE TABLE TB_ENDERECO(
	ID_ENDERECO INT NOT NULL auto_increment UNIQUE,
    LOGRADOURO VARCHAR(100) NOT NULL,
    NUMERO INT NOT NULL,
    BAIRRO VARCHAR(50),
    COMPLEMENTO VARCHAR(75),
    CEP INT(8),
    CIDADE VARCHAR(50) NOT NULL,
    SIGLA_ESTADO CHAR(2) NOT NULL,
    PAIS VARCHAR(30) NOT NULL,
    ID_PESSOA INT NOT NULL,
    PRIMARY KEY (ID_ENDERECO),
    FOREIGN KEY (ID_PESSOA) REFERENCES TB_PESSOA(ID_PESSOA)
);

CREATE TABLE TB_GRUPO(
	ID_GRUPO INT NOT NULL auto_increment UNIQUE,
    TIPO VARCHAR(50) NOT NULL,
    PRIMARY KEY(ID_GRUPO)
);

CREATE TABLE TB_PERTENCE(
	ID_GRUPO INT NOT NULL,
    ID_PESSOA INT NOT NULL,
    PRIMARY KEY (ID_GRUPO,ID_PESSOA),
    FOREIGN KEY (ID_GRUPO) REFERENCES TB_GRUPO(ID_GRUPO),
    FOREIGN KEY (ID_PESSOA) REFERENCES TB_PESSOA(ID_PESSOA)
);

CREATE TABLE TB_COMPROMISSO(
	ID_COMPROMISSO INT NOT NULL auto_increment UNIQUE,
    TITULO VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(500),
    LOCAL_COMPROMISSO VARCHAR(50) NOT NULL,
    DATA_INICIO DATE NOT NULL,
    DATA_FINAL DATE NOT NULL,
    HORARIO_INICIO TIME NOT NULL,
    HORARIO_FINAL TIME NOT NULL,
    ID_PESSOA INT NOT NULL,
    FOREIGN KEY (ID_PESSOA) REFERENCES TB_PESSOA(ID_PESSOA)
);