CREATE DATABASE AGENDA;

USE AGENDA;

CREATE TABLE TB_PESSOA(
	ID_PESSOA INT NOT NULL auto_increment UNIQUE,
    NOME VARCHAR(100) NOT NULL,
    DATA_NASC DATE NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    TELEFONE1 INT NOT NULL,
    TELEFONE2 INT,
    FOTO MEDIUMBLOB,
    PRIMARY KEY (ID_PESSOA)
);

CREATE TABLE TB_ESTADO(
	SIGLA CHAR(2) NOT NULL,
    NOME VARCHAR(20) NOT NULL,
    PRIMARY KEY (SIGLA)
);

CREATE TABLE TB_ENDERECO(
	ID_ENDERECO INT NOT NULL auto_increment UNIQUE,
    LOGRADOURO VARCHAR(100) NOT NULL,
    NUMERO INT NOT NULL,
    BAIRRO VARCHAR(50) NOT NULL,
    COMPLEMENTO VARCHAR(75) NOT NULL,
    CIDADE VARCHAR(50) NOT NULL,
    CEP INT(8) NOT NULL,
    SIGLA_ESTADO CHAR(2) NOT NULL,
    ID_PESSOA INT NOT NULL,
    PRIMARY KEY (ID_ENDERECO),
    FOREIGN KEY (SIGLA_ESTADO) REFERENCES TB_ESTADO(SIGLA),
    FOREIGN KEY (ID_PESSOA) REFERENCES TB_PESSOA(ID_PESSOA)
);

CREATE TABLE TB_USUARIO(
	ID_USUARIO INT NOT NULL auto_increment UNIQUE,
    USUARIO VARCHAR(50) NOT NULL UNIQUE,
    SENHA_PESSOA VARCHAR(50) NOT NULL,
    ID_PESSOA INT NOT NULL,
    PRIMARY KEY (ID_USUARIO),
    FOREIGN KEY (ID_PESSOA) REFERENCES TB_PESSOA(ID_PESSOA)
);

CREATE TABLE TB_GRUPO(
	ID_GRUPO INT NOT NULL auto_increment UNIQUE,
    TIPO VARCHAR(50) NOT NULL,
    PRIMARY KEY(ID_GRUPO)
);

CREATE TABLE TB_PERTENCE(
	ID_GRUPO INT NOT NULL,
    ID_PESSOA INT NOT NULL,
    FOREIGN KEY (ID_GRUPO) REFERENCES TB_GRUPO(ID_GRUPO),
    FOREIGN KEY (ID_PESSOA) REFERENCES TB_PESSOA(ID_PESSOA)
);

CREATE TABLE TB_AGENDA(
	ID_AGENDA INT NOT NULL auto_increment UNIQUE,
    DATA_INICIO DATE NOT NULL,
    DATA_FINAL DATE NOT NULL,
    HORARIO_INICIO TIME NOT NULL,
    HORARIO_FINAL TIME NOT NULL
);

CREATE TABLE TB_COMPROMISSO(
	ID_COMPROMISSO INT NOT NULL auto_increment UNIQUE,
    TITULO VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(500),
    LOCAL_COMPROMISSO VARCHAR(50) NOT NULL,
    ID_PESSOA INT NOT NULL,
    ID_AGENDA INT NOT NULL,
    FOREIGN KEY (ID_PESSOA) REFERENCES TB_PESSOA(ID_PESSOA),
    FOREIGN KEY (ID_AGENDA) REFERENCES TB_AGENDA(ID_AGENDA)
);